package it.pagopa.pn.downtime.model;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.Setter;


@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "Event")
public class Event implements Serializable {
		private static final long serialVersionUID = 1L;
		private String uuid;
	    private String timestamp;
	    private String yearMonth;
	    private String functionality;
	    private String status;
	    private String sourceType;
	    private String source;

	    @DynamoDBHashKey
	    @DynamoDBAutoGeneratedKey
	    public String getUuid() {
	        return uuid;
	    }

	    @DynamoDBAttribute
		public String getTimestamp() {
			return timestamp;
		}
	    
	    @DynamoDBAttribute
		public String getYearMonth() {
			return yearMonth;
		}
	    
	    @DynamoDBAttribute
		public String getFunctionality() {
			return functionality;
		}
	    
	    @DynamoDBAttribute
		public String getStatus() {
			return status;
		}
	    
	    @DynamoDBAttribute
		public String getSourceType() {
			return sourceType;
		}
	    
	    @DynamoDBAttribute
		public String getSource() {
			return source;
		}


}
