AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

Resources:

  ### Queue that receive safe-storage notification to DOWNTIME LOGS ###
  InternalEventQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-downtime_logs_internal_events'
        DelaySeconds: 1

  Event:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: Downtime-Event
      AttributeDefinitions:
        - AttributeName: idEvent
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: idEvent
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification: 
        StreamViewType: NEW_IMAGE

  Log:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: Downtime-DowntimeLogs
      AttributeDefinitions:
        - AttributeName: functionalityStartYear
          AttributeType: S
        - AttributeName: startDate
          AttributeType: S
        - AttributeName: endDate
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: DowntimeLogsGSIndex
          KeySchema:
            - AttributeName: functionalityStartYear
              KeyType: HASH
            - AttributeName: endDate
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      KeySchema:
        - AttributeName: functionalityStartYear
          KeyType: HASH
        - AttributeName: startDate
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification: 
        StreamViewType: NEW_IMAGE

Outputs:
  
  # External channels outputs
  InternalEventQueueName:
    Value: !GetAtt InternalEventQueue.Outputs.QueueName
    Description: internal events queue name
  InternalEventQueueURL:
    Value: !GetAtt InternalEventQueue.Outputs.QueueURL
    Description: internal events queue URL
  InternalEventQueueARN:
    Value: !GetAtt InternalEventQueue.Outputs.QueueARN
    Description: internal events queue ARN
  InternalEventQueueAlarmARN:
    Value: !GetAtt InternalEventQueue.Outputs.SqsDLQAlarmArn
    Description: internal events queue alarm ARN

  EventTableName:
    Description: Event table name
    Value: !Ref Event
  EventDynamoTableArn:
    Description: ARN of dynamodb table containing event
    Value: !Sub '${Event.Arn}'

  LogTableName:
    Description: Log table name
    Value: !Ref Log
  LogDynamoTableArn:
    Description: ARN of dynamodb table containing log
    Value: !Sub '${Log.Arn}'
